import {WebXRHandJoint} from '@babylonjs/core';

export const JOINTS_LIST = [
	WebXRHandJoint.WRIST,
	WebXRHandJoint.THUMB_METACARPAL,
	WebXRHandJoint.THUMB_PHALANX_PROXIMAL,
	WebXRHandJoint.THUMB_PHALANX_DISTAL,
	WebXRHandJoint.THUMB_TIP,
	
	WebXRHandJoint.INDEX_FINGER_METACARPAL,
	WebXRHandJoint.INDEX_FINGER_PHALANX_PROXIMAL,
	WebXRHandJoint.INDEX_FINGER_PHALANX_INTERMEDIATE,
	WebXRHandJoint.INDEX_FINGER_PHALANX_DISTAL,
	WebXRHandJoint.INDEX_FINGER_TIP,
	
	WebXRHandJoint.MIDDLE_FINGER_METACARPAL,
	WebXRHandJoint.MIDDLE_FINGER_PHALANX_PROXIMAL,
	WebXRHandJoint.MIDDLE_FINGER_PHALANX_INTERMEDIATE,
	WebXRHandJoint.MIDDLE_FINGER_PHALANX_DISTAL,
	WebXRHandJoint.MIDDLE_FINGER_TIP,
	
	WebXRHandJoint.RING_FINGER_METACARPAL,
	WebXRHandJoint.RING_FINGER_PHALANX_PROXIMAL,
	WebXRHandJoint.RING_FINGER_PHALANX_INTERMEDIATE,
	WebXRHandJoint.RING_FINGER_PHALANX_DISTAL,
	WebXRHandJoint.RING_FINGER_TIP,
	
	WebXRHandJoint.PINKY_FINGER_METACARPAL,
	WebXRHandJoint.PINKY_FINGER_PHALANX_PROXIMAL,
	WebXRHandJoint.PINKY_FINGER_PHALANX_INTERMEDIATE,
	WebXRHandJoint.PINKY_FINGER_PHALANX_DISTAL,
	WebXRHandJoint.PINKY_FINGER_TIP
];