import {WebXRHandJoint}         from '@babylonjs/core/XR/features/WebXRHandTracking';


export const JointsNames:(keyof typeof WebXRHandJoint)[] = [
	'WRIST',
	
	'THUMB_METACARPAL',
	'THUMB_PHALANX_PROXIMAL',
	'THUMB_PHALANX_DISTAL',
	'THUMB_TIP',
	
	'INDEX_FINGER_METACARPAL',
	'INDEX_FINGER_PHALANX_PROXIMAL',
	'INDEX_FINGER_PHALANX_INTERMEDIATE',
	'INDEX_FINGER_PHALANX_DISTAL',
	'INDEX_FINGER_TIP',
	
	'MIDDLE_FINGER_METACARPAL',
	'MIDDLE_FINGER_PHALANX_PROXIMAL',
	'MIDDLE_FINGER_PHALANX_INTERMEDIATE',
	'MIDDLE_FINGER_PHALANX_DISTAL',
	'MIDDLE_FINGER_TIP',
	
	'RING_FINGER_METACARPAL',
	'RING_FINGER_PHALANX_PROXIMAL',
	'RING_FINGER_PHALANX_INTERMEDIATE',
	'RING_FINGER_PHALANX_DISTAL',
	'RING_FINGER_TIP',
	
	'PINKY_FINGER_METACARPAL',
	'PINKY_FINGER_PHALANX_PROXIMAL',
	'PINKY_FINGER_PHALANX_INTERMEDIATE',
	'PINKY_FINGER_PHALANX_DISTAL',
	'PINKY_FINGER_TIP'
]